# Debug config.
Debug : false

# Sound config. Set the volume to 0 to mute the sound.
SortingSound :
  Name : minecraft:block.note_block.pling
  Value : 0.1

# Other config (Force limit array size at 760).
LimitLength : false
MaxActionBarArrayLength : 332