## YAML Template.
---
main: com.hao.haovsort.Main
name: HaoVSort
version: 1.1.0
description: This plugin can visualize an sorting algorithm with a color scale. -Made in Thailand.
author: Sittipat Tepsutar
api-version: 1.13
softdepend: [NoteBlockAPI]
commands:
    sort:
      description: Main plugin commands.
      usage: /<command>
      permission: haovsort.commands.sort
      permission-message: You do not have permission to use this command.
    sortstop:
      description: Stop visualize
      usage: /<command> <player>
      permission: haovsort.commands.sortstop
      permission-message: You do not have permission to use this command.
    sortdebug:
      description: Debug
      usage: /<command>
      permission: haovsort.debug
      permission-message: You do not have permission to use this command.
    sortcustom:
      description: Custom command.
      usage: /<command>
      permission: haovsort.commands.sortcustom
      permission-message: You do not have permission to use this command.
    sortreload:
      description: Reload the plugin
      usage: /<command>
      permission: haovsort.reload
      permission-message: You do not have permission to use this command.
    sortdelay:
      description: Set new delay to sorting algorithm player.
      usage: /<command>
      permission: haovsort.delay
      permission-message: You do not have permission to use this command.
permissions:
  haovsort.*:
    description: Give access to HaoVSort whole.
    default: op
    children:
      haovsort.command.sort: true
      haovsort.command.sortstop: true
      haovsort.command.sortcustom: true
      haovsort.debug: true
      haovsort.reload: true
      haovsort.command.delay: true
  haovsort.command.*:
    description: Allows player to use all command in HaoVSort plugin.
    children:
      haovsort.command.sort: true
      haovsort.command.sortstop: true
      haovsort.command.sortcustom: true
      haovsort.command.delay: true
    default: op
  haovsort.command.sort:
    description: Allows player to use /sort command.
    default: op
  haovsort.command.sortstop:
    description: Allows player to use /sortstop command.
    default: op
  haovsort.command.delay:
    description: Allows player to use /sortdelay command.
    default: op
  haovsort.debug:
    description: Allows player to debug HaoVSort plugin.
    default: op
  haovsort.reload:
    description: Allows player to reload the plugin.
    default: op