## YAML Template.
---
main: com.hao.haovsort.Main
name: HaoVSort
version: 1.0.0-SNAPSHOT
description: This plugin can visualize an sorting algorithm with a color scale. -Made in Thailand.
author: Sittipat Tepsutar
commands:
    sort:
      description: Main plugin commands.
      usage: /<command>
      permission: haovsort.commands.sort